version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: registry.portus.my:5000/user1/my-web-server-master:1.0
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    networks:
      - webnet
networks:
  webnet:

