COPY ./target/ /arrowhead/eventhandler/
COPY ./config/ /arrowhead/eventhandler/config/
WORKDIR /arrowhead/eventhandler
#ENTRYPOINT ["java", "--add-modules", "java.xml.bind", "-cp", "lib/*:*", "-jar", "eventhandler-4.0.jar", "-d", "-daemon", "> insecure_eventhandler.log &"]
ENTRYPOINT ["java", "-cp", "lib/*:*", "-jar", "eventhandler-4.0.jar", "-d", "-daemon" ]
